/*!
 * \file src/compat/mb_api.cpp
 * \author Shawn Chin
 * \date October 2012
 * \copyright Copyright (c) 2012 STFC Rutherford Appleton Laboratory
 * \copyright Copyright (c) 2012 University of Sheffield
 * \copyright GNU Lesser General Public License
 * \brief Mock Implementation of C API for message board access
 * \note These routines should instead be generated by the parser for each model
 */

