/*!
 * \file config.hpp
 * \author Shawn Chin
 * \date October 2012
 * \copyright Copyright (c) 2012 STFC Rutherford Appleton Laboratory
 * \copyright Copyright (c) 2012 University of Sheffield
 * \copyright GNU Lesser General Public License
 * \brief Load platform-specific defines (generated by autoconf).
 *
 * This file should only be included by .cpp files, not headers.
 */
#ifndef CONFIG_HPP_
#define CONFIG_HPP_
#include "flame2/cfg.h"
#endif  // CONFIG_HPP_
